name: Trips Go CI

on:
  push:
    branches: 
    - master
    - features/trips
    paths:
    - apis/trips
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install dependencies
      run: go get apis/trips/

    - name: Test
      run: go test -v apis/trips/tests
