name: .NET

on:
  workflow_dispatch:
  push:
    branches: 
    - master 
    - features/poi
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.202
    - name: Restore dependencies
      run: dotnet restore apis/poi/poi.sln
    - name: Build
      run: dotnet build --no-restore apis/poi/web/poi.csproj
    - name: Test
      run: dotnet test --no-build --no-restore --verbosity normal apis/poi/poi.sln
