name: .NET

on:
  workflow_dispatch:
  push:
    branches: 
    - master 
    - features/poi
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.202


      
    - name: Restore dependencies
      run: dotnet restore apis/poi/web/*.csproj
      
    - name: Build Web
      run: dotnet build --configuration Release --no-restore apis/poi/web/poi.csproj
      
    - name: Build Unit Test
      run: dotnet build --configuration Release --verbosity normal apis/poi/tests/UnitTests/UnitTests.csproj

    - name: Test dotnet unit
      run: dotnet test --no-restore --verbosity normal apis/poi/tests/UnitTests
      

